# Generated by Django 3.1.6 on 2021-02-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRequest', '0002_auto_20210216_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
